import { Injectable } from '@angular/core';
import * as ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

@Injectable({
  providedIn: 'root'
})
export class ExcelExportService {

  async exportToFile(
    jsonData: any[],
    fileName: string,
    headerMap?: Record<string, string>,
    format: 'excel' | 'csv' | 'pdf' = 'excel'
  ): Promise<void> {

    if (!jsonData || jsonData.length === 0) {
      console.warn('⚠️ No data to export');
      return;
    }

    let exportData = jsonData;
    if (headerMap) {
      exportData = jsonData.map(row => {
        const newRow: any = {};
        for (const key in headerMap) {
          const actualKey = Object.keys(row).find(k => k.toLowerCase() === key.toLowerCase());
          newRow[headerMap[key]] = actualKey ? row[actualKey] : '';
        }
        return newRow;
      });
    }

    const headers = Object.keys(exportData[0]);
    const currentDate = new Date().toLocaleDateString();

    // ✅ EXCEL
    // ================= EXCEL =================
if (format === 'excel') {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(fileName); // Sheet name = fileName

  // Top-left: Report name
  worksheet.insertRow(1, [fileName]); 
  worksheet.mergeCells(1, 1, 1, headers.length);
  const titleCell = worksheet.getCell('A1');
  titleCell.font = { bold: true, size: 14 };
  titleCell.alignment = { horizontal: 'left', vertical: 'middle' };

  // Header row
  worksheet.insertRow(2, headers);

  // Data rows
  exportData.forEach(data => worksheet.addRow(Object.values(data)));

  // Last row, last column: Generated by CRPL
  // const lastRowNum = worksheet.rowCount + 1;
  // worksheet.getCell(lastRowNum, headers.length).value = 'Generated by CRPL';

  // Style header
  const headerRow = worksheet.getRow(2);
  headerRow.font = { bold: true, color: { argb: '000000' } };
  headerRow.alignment = { horizontal: 'center', vertical: 'middle' };
  headerRow.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'F2F2F2' } };
  headerRow.eachCell(cell => {
  cell.border = {
    top: { style: 'thin', color: { argb: '000000' } },
    left: { style: 'thin', color: { argb: '000000' } },
    bottom: { style: 'thin', color: { argb: '000000' } },
    right: { style: 'thin', color: { argb: '000000' } }
  };
});
  // Column width auto adjust
  (worksheet.columns as any).forEach((column: any) => {
    let maxLength = 0;
    column.eachCell({ includeEmpty: true }, (cell: any) => {
      const len = cell.value ? cell.value.toString().length : 10;
      if (len > maxLength) maxLength = len;
    });
    column.width = maxLength + 5;
  });

  // Alternate row coloring
  worksheet.eachRow((row, rowNumber) => {
    if (rowNumber > 2 && rowNumber % 2 === 0) {
      row.eachCell(cell => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'F2F2F2' } };
      });
    }
  });

  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  saveAs(blob, `${fileName}.xlsx`);
  return;
}

// ================= CSV =================
// if (format === 'csv') {
//   let csvContent = `${fileName}\n`; // Top-left report name
//   csvContent += headers.join(',') + '\n';
//   exportData.forEach(row => {
//     csvContent += Object.values(row).join(',') + '\n';
//   });
//   // const lastRow = Array(headers.length).fill('');
//   // lastRow[headers.length - 1] = 'Generated by CRPL'; // Bottom-right
//   // csvContent += lastRow.join(',');

//   const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
//   saveAs(blob, `${fileName}.csv`);
//   return;
// }
if (format === 'csv') {
  // File name "visual bold" ke liye decorate kar diya
  let csvContent = `*** ${fileName.toUpperCase()} ***\n`; // Top-left report name

  // Header "visual bold" (uppercase)
  csvContent += headers.map(h => h.toUpperCase()).join(',') + '\n';

  // Data
  exportData.forEach(row => {
    csvContent += Object.values(row).join(',') + '\n';
  });

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, `${fileName}.csv`);
  return;
}



// ================= PDF =================
if (format === 'pdf') {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'A4' });

  // Top-left: Report name
  doc.setFontSize(14);
  doc.setFont('', 'bold');
  doc.text(fileName, 40, 30);

  // Top-right: Date
  const currentDate = new Date().toLocaleDateString();
  doc.setFontSize(10);
  doc.setFont('', 'normal');
  doc.text(`Date : ${currentDate}`, doc.internal.pageSize.getWidth() - 100, 30);

  // Table
  const tableBody = exportData.map(row => Object.values(row)) as (string | number)[][];
  autoTable(doc, {
    startY: 50,
    head: [headers],
    body: tableBody,
    theme: 'grid',
    headStyles: { fillColor: [200, 200, 200], textColor: [2, 0, 0] },
    styles: { fontSize: 9, cellPadding: 4 },
  });

  doc.save(`${fileName}.pdf`);
  return;
}
  }
}